FROM python:3.10-slim

WORKDIR /app

# Installation des dépendances système nécessaires pour psycopg2
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir fastapi uvicorn pandas psycopg2-binary sqlalchemy

COPY load.py /app/load.py

CMD ["uvicorn", "load:app", "--host", "0.0.0.0", "--port", "8000"]