FROM python:3.10-slim

WORKDIR /app

# 1. Copier et installer les dépendances (met en cache l'installation)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2. Copier explicitement les scripts pour être sûre qu'ils soient côte à côte dans /app
COPY transform.py /app/
COPY pipeline_ml.py /app/

# 3. Lancer le serveur Uvicorn
CMD ["uvicorn", "transform:app", "--host", "0.0.0.0", "--port", "8000"]